#! /bin/sh

sxhkd &
nitrogen --restore &
dunst &
/home/paul/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        2
bspc config window_gap			12
bspc config top_padding         15

bspc config split_ratio        	 0.50
bspc config borderless_monocle 	 false
bspc config gapless_monocle    	 false

bspc rule -a Emacs state=tiled
