#!/bin/bash

## Created By Aditya Shakya

MENU="$(echo -e " Lock\n Logout\n Reboot\n Shutdown" | dmenu -fn "TerminessTTF Nerd Font:style=Medium")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) sudo systemctl restart lightdm;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
